spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
  h2:
    console:
      enabled: true
      path: /h2
  output:
    ansi:
      enabled: ALWAYS
